### ISSUE TITLE
Serializer::serialize_bytes does not serialize the size prefix

### ISSUE THREAD

**Issue by okready** [jamesmunns/postcard#21]
The `Serializer::serialize_bytes` should include the number of bytes serialized so that `Deserializer::deserialize_bytes` can correctly read the number of bytes back when deserializing, but the current `serialize_bytes` implementation omits this. This breaks serialization for types that use `serialize_bytes` and `deserialize_bytes`, such as the `Bytes` and `BytesMut` types from the `bytes` crate or `CStr` and `CString`.

#### Cargo.toml

```toml
[package]
name = "serialize_bytes_test"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = { version = "0.5.4", features = ["serde"] }
heapless = "0.5.5"
postcard = "0.5.0"
```

#### src/main.rs

```rust
use bytes::BytesMut;
use heapless::{consts::U16, Vec};
use postcard::{from_bytes, to_vec};

fn main() {
    let x = BytesMut::from(&[1u8, 2, 3, 4][..]);
    let serialized: Vec<u8, U16> = to_vec(&x).unwrap();
    let deserialized: BytesMut = from_bytes(&serialized).unwrap();
    assert_eq!(deserialized, x);
}
````
